version: '2'
services:
 
    db:
        image: postgres:latest
        container_name: odoodbcon
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: oddo1
            PGDATA: /var/lib/postgresql/data/odoo
        volumes:
               - "dbodoodata:/var/lib/postgresql/data/odoo"
    
    odooapp:
        image: odoo:latest
        container_name: odooweb
        ports:
            - "8080:8069"
        restart: always
        environment:
            - HOST=db
            - User=odoo
            - PASSWORD=oddo1
        depends_on:
            - db
        volumes:
               - "webodoodata:/var/lib/odoo"


volumes:
    dbodoodata:
    webodoodata: